#ifndef DEFINATIONS_H
#define DEFINATIONS_H

#define ESP_WIFI_SSID      CONFIG_ESP_WIFI_SSID
#define ESP_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
#define ESP_WIFI_CHANNEL   CONFIG_ESP_WIFI_CHANNEL
#define MAX_STA_CONN       CONFIG_ESP_MAX_STA_CONN

#define MAX_SOCKETS 7

#define WIFI_TAG "WiFi"
#define MAIN_TAG "Main"
#define SERV_TAG "Server"

#endif